package com.assignment.draftly.enums;

public enum DraftActionType {
    DRAFT_CREATED,
    DRAFT_EDITED,
    DRAFT_REGENERATED,
    DRAFT_APPROVED,
    DRAFT_REJECTED,
    EMAIL_SENT,
    GMAIL_DRAFT_CREATED,
    GMAIL_DRAFT_UPDATED,
    GMAIL_DRAFT_DELETED,
    GMAIL_API_ERROR,
    AI_GENERATION_STARTED,
    AI_GENERATION_COMPLETED,
    AI_GENERATION_FAILED
}
